version: "3.4"

services:
  nginx:
    image: nginx:1.15.7
    ports:
      - 8081:80
    links:
      - fpm
      - mysql

  fpm:
    build: ./Docker/php

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
